<?php require 'templates/header.phtml' ?>

<?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
    <?php require 'templates/form_add_book.phtml' ?>
<?php endif ?>

<table class="table">

    <thead>
        <tr class="text-nowrap">
            <th scope="col">ID</th>
            <th scope="col">Título</th>
            <th scope="col">Año de Publicación</th>
            <th scope="col">Autor</th>
            <th scope="col">Autor ID</th>
            <th scope="col">Sinopsis</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($books as $book) : ?>
            <tr>
                <th scope="row"><?= $book->id_book ?></th>
                <td><?= $book->title ?></td>
                <td><?= $book->publication_date ?></td>
                <td><?= $book->author->name ?></td>
                <td class="fw-bold"><?= $book->author->id_author ?></td>
                <td class=" text-center"><?= $book->synopsis ?></td>
                <?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
                    <td><a href='eliminarLibro/<?= $book->id_book ?>' type='button' class='btn btn-danger'>Borrar</a></td>
                    <td><a href='editarLibro/<?= $book->id_book ?>' type='button' class="btn btn-warning">Editar</a></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    </tbody>

</table>

<p class="mt-3 fst-italic"><b>Mostrando <?= $count ?> libros</b></p>

<?php require 'templates/footer.phtml' ?>